### ISSUE TITLE
Popup - No history stats

### ISSUE THREAD

**Issue by Imperial-Guard** [thomasloven/hass-browser_mod#129]
With the latest version of the browser mod 1.1.15 and Home Assistant 0.113.3 the popup mod is working only by clicking on it I don't see any historical data.

![image](https://user-images.githubusercontent.com/33509000/89184559-502c1400-d599-11ea-80cd-f6b42ee96c0c.png)
![image](https://user-images.githubusercontent.com/33509000/89184622-65a13e00-d599-11ea-9b47-27a308e611ff.png)

**Comment by ASNNetworks** [comment]
Are you sure your using the standard more info dialog? Or are you perhaps using the ['more-info' custom card](https://github.com/thomasloven/lovelace-more-info-card) as a popup service call with browser_mod? If so: I think more-info custom card is bugged, then you should report this bug on that repo instead of browser_mod. All my more info custom cards that I use that don't show history either. The cards that use the default more info dialogue do show the history however.

**Comment by KTibow** [comment]
If you customize the popup card and change it, you'll need to manually add the graph.

**Comment by thomasloven** [comment]
This is likely unrelated to browser_mod and instead an issue with the card you are using in the popup.
