### ISSUE TITLE
Popup in another window

### ISSUE THREAD

**Issue by Stupco** [thomasloven/hass-browser_mod#139]
I find this issue only when I have more than one window open with HA, when I click a card on the front end, the popup will display on the other window even if it's looking at the Developer tab for example.

I thought I broke it completely until I stumbled across it in the wrong window.

Obvs not a massive issue as I can just close the other windows (don't need more than one often, just when I'm testing), but thought I should raise it all the same!

browser_mod version 1.1.6 installed via HACS
Home Assistant 0.115.2 running as a LXC in Proxmox
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 245
virtualenv | false

**Comment by KTibow** [comment]
Yeah, when the browser receives a message, it should only display it if it detects focus.

**Comment by isabellaalstrom** [comment]
This is expected behavior, it shows up on the last refreshed window/tab.

**Comment by Stupco** [comment]
@isabellaalstrom , if that is the case, please close. :)

**Comment by isabellaalstrom** [comment]
I cannot close, but you can do that yourself :)

**Comment by jdtechsol** [comment]
Say I have 3 tabs open:
A) Overview Dashboard (Raw Editor)
B) Overview Dashboard (Default View)
C) Developer Tools

In Tab B I click a button card that triggers browser_mod.popup and I immediately see the popup in that Tab, but If I go to Tabs A/C the popup will open as well, even if I've closed the popup in Tab B beforehand. You are telling me THIS is expected behavior? What if I want to have the popup show up in the tab from which it was called and nowhere else (including not showing up in other tabs)?
