### ISSUE TITLE
Device state attibute warning

### ISSUE THREAD

**Issue by manustars** [thomasloven/hass-browser_mod#305]
My Home Assistant version: supervisor-2022.01.1

**What I am doing:**
Recive a lot of log warning

**What I expected to happen:**

**What happened instead:**

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:583
First occurred: 8 marzo 2022, 01:07:08 (6 occurrences)
Last logged: 21:55:32

Entity media_player.cd066e9b_1a387def (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.cd066e9b_1a387def (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity media_player.3e6bb764_575252d4 (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.3e6bb764_575252d4 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.3e6bb764_575252d4 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X ] Have made sure I am using the latest version of the plugin.

- [ X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by MrThiemann** [comment]
i have the same issues... Before I open a new case, I'll take a look here.

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:601
First occurred: 06:06:42 (3 occurrences)
Last logged: 06:06:42

Entity media_player.browser_mod_b25b689a_ccfae132 (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.browser_mod_b25b689a_ccfae132 (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.browser_mod_b25b689a_ccfae132 (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.`

Since the entries are still very "few", I cannot say since when this error has existed.

**Comment by curtisdr** [comment]
Same issue & wonder if it has any relation to why my alarm clock did not sound twice this week, and it uses media.player.[browser mod entity] to do so.

**Comment by niemyjski** [comment]
I'm getting hundreds of these.
