### ISSUE TITLE
Browser Mod 2.0 media player issues

### ISSUE THREAD

**Issue by SiriosDev** [thomasloven/hass-browser_mod#366]
My Home Assistant version: 2022.8.7

**What I am doing:**
Trying playing media on various devices (not at the same time)

**What I expected to happen:**
All players working

**What happened instead:**
The player works only when I'm on "local URL"
The one in the android app does not appear to be available
The one reached by an external URL (Nginx reverse) from the UI results in play but not play anything
(except android all the other tests are done on chromium-based browsers{chrome, edge, opera, ecc} )

**Minimal** steps to reproduce:
Set up Browser Mod on the browsers (internal and external URL) and try to reproduce something.

P.S.
Videos don't work anyway, but honestly, I don't know if browser mod has ever done so.

**Comment by thomasloven** [comment]
Videos do work with Browser Mod 2.0.

For audio playback your Home Assistant URL under Settings -> System -> Network will need to be setup correctly.

The URL for the media file that Home Assistant sends to the player (Browser Mod or otherwise) will be based on the URL for local network access since it is assumed that players are on your local network.
This is a Home Assistant limitation and nothing Browser Mod can change.

I suggest setting up your network such that you access Home Assistant through your external URL even on your local network.

**Comment by SiriosDev** [comment]
if you men this
![image](https://user-images.githubusercontent.com/26876994/188992659-9093d2b5-9f08-4126-aff1-6b6fdf773a6b.png)
i have already setted up
