### ISSUE TITLE
Change name of another browser from admin account?

### ISSUE THREAD

**Issue by jatgm1** [thomasloven/hass-browser_mod#465]
Is there a way to change the name of some one else's browser login instance? Like can this be added so if someone sets their device name to "not intruder" for instance I can change it to "unknown device" or "brother who was joking around" or whatever?

**Comment by jazzyisj** [comment]
Changing the browser_mod id from different device likely isn't a good idea because it is recommended to refresh the page for browser_mod to load and work correctly.

If you are concerned about someone mucking with their browser_mod settings then just lock it from an administrator account.  This is exactly why that feature exists.

![image](https://user-images.githubusercontent.com/44064559/194465235-b49b8a7a-f361-4444-9ed3-3408f2841104.png)

**Comment by thomasloven** [comment]
Correct. It can only be changed from the browser in question.
