### ISSUE TITLE
Browser Mod Icone

### ISSUE THREAD

**Issue by tempus2016** [thomasloven/hass-browser_mod#521]
Not a bug, but how do we disable the browser mod icon that appears in the lower right corner?  It's quite annoying.

**Comment by niraviry** [comment]
This seems to activate the browser_mod for the specific browser. The browser seems to be unavailable before pressing the icon.
The problem is that in some cases (in my case a tablet with Companion), the icon is under the bottom home icon in the menu so it is not reachable.
On the iOS version it is OK. It needs fixing.

**Comment by niraviry** [comment]
Actually, the icon needs to be on the opposite side of the menu bar. It is a bug.
