### ISSUE TITLE
Dont use Browser ID but use specail User / URL / cookie? 

### ISSUE THREAD

**Issue by Peda1996** [thomasloven/hass-browser_mod#532]
As the Browser id keeps changing quite often, would it be possible to assign the Browser mod instance only for special created users (ec: create kiosk User that is logge in at the Wall mounted tablet) ?

An alternative would be to use special URLs or cookies as identifiers.

Would a change like this be possible?

**Comment by ribbal** [comment]
I’m relatively new to browser mod. If you manually set the browser id to something sensible (e.g. ‘laptop-chrome’) does that prevent the browser id from changing.

That’s what I have done, but I’ve only been using it for less than a week.

**Comment by Peda1996** [comment]
Hi, how have you done this? Did you use an Firefox / Chrome / edge addon to archive this change?

And if yes, how did you do this?

**Comment by ribbal** [comment]
Select 'Browser Mod' from the sidebar:

![image](https://user-images.githubusercontent.com/30695106/216300589-106347f8-ebd0-4324-9be0-be0c1935b1c4.png)

**Comment by Peda1996** [comment]
I dont think that this is gonna keep the Browser id from changing.

**Comment by thomasloven** [comment]
Cookies are infinitely more volatile than the browser ID.
The browserID is stored in the same was as the id of the currently logged in user, so you'd need to log in as often as you need to reset your browser ID now.

All settings can be done per user instead of per browser. Only service calls are browser-bound.
